apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moneyexchange
  labels:
    app: moneyexchange
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: moneyexchange
    spec:
      containers:
      - name: moneyexchange
        image: gcr.io/moneyexchange-242913/moneyexchange:v0.0.1
        ports:
          - containerPort: 8080
        env:
          - name: NODE_ENV
            value: "production"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
